/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import com.carlos.OuputDocs.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author benjamin
 */
public class CaracteristicaReportesJDialog extends javax.swing.JDialog {

    /**
     * Creates new form CaracteristicaReportesJDialog
     */
    public CaracteristicaReportesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("REPORTES DE TIENDA");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRealizarreporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRealizarreporte.setText("Realizar Reporte");
        jButtonRealizarreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarreporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jButtonRealizarreporte)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jButtonRealizarreporte)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarreporteActionPerformed
        // TODO add your handling code here:
        JFileChooser ventanaDeGuardado = new JFileChooser();
        //se establece el modo de trabajo de Jfilechooser
        ventanaDeGuardado.setFileSelectionMode(0);
        ventanaDeGuardado.setDialogTitle("Guardar en");
        //filtro para el tipo de archivos de guadado del archivo
        FileNameExtensionFilter filtroExportacion=new FileNameExtensionFilter("HTML","html");
        ventanaDeGuardado.setFileFilter(filtroExportacion);
        //extremos el directorio por defento donde aparecera el jFileChooser
        String src = ventanaDeGuardado.getCurrentDirectory().toString();
        //Nombre por defecto del archivo a generar
        String nameFile = "REPORTE.html";
        //Completado del path completo con nombre de archivo
        src= src +"/"+nameFile;
        //se genera una variable de tipo file para almacenar el path y asignarlo al JFileChooser
        File archivo = new File(src);
        //Asignacion del archivo seleccionado
        ventanaDeGuardado.setSelectedFile(archivo);
        //condicion si se da en el boton de aceptar en la interfaz del JFileChooser
        if(ventanaDeGuardado.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            /*Extraemos nuevamente el path del archivo por si este 
            cambio de parametros como de directorio como el nombre del archivo a guardar
            */
            File guardado = ventanaDeGuardado.getSelectedFile();
            //comprueba si el archivo termina en extencion .html
            if(guardado.getName().endsWith(".html")){
                //comprueba si hay un archivo con las misma caracteristicas
                if(!(guardado.exists()))
                {
                    //usa un objeto de tipo GenerateHTML para crear el archivo de salida
                    GenerateHTML html = new GenerateHTML(guardado);
                    html.Generate();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Existe un archivo con el mismo nombre guardelo con otro nombre");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Tipo de archivo no soportado exporte nuevamente la infomarmacion");
            }
        }
    }//GEN-LAST:event_jButtonRealizarreporteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRealizarreporte;
    // End of variables declaration//GEN-END:variables
}
