/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import com.carlos.DBSuport.*;
import com.carlos.Entities.*;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class EntregaProductoJDialog extends javax.swing.JDialog {
    private String tiendaSeleccionada;
    private ConsultasDB consultaDB = new ConsultasDB();
    private ModificacionesDB modificarDB = new ModificacionesDB();
    private RegistroDB registrarEnDB = new RegistroDB();
    private Connection baseDeDatos;
    /**
     * Formulario en el cual se ingresan datos de pedidos para su entrega posteriormente realizar su transaccion venta y registro en el sistema
     * @param parent
     * @param modal
     * @param tienda
     * @param conexionBaseDatos
     */
    public EntregaProductoJDialog(java.awt.Frame parent, boolean modal,String tienda,Connection conexionBaseDatos) {
        super(parent, modal);
        this.baseDeDatos=conexionBaseDatos;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ENTREGA DE PRODUCTO");
        tiendaSeleccionada=this.consultaDB.codigoTienda(tienda,this.baseDeDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoPedido = new javax.swing.JFormattedTextField();
        jButtonBuscarPedido = new javax.swing.JButton();
        jButtonLimpiarBusqueda = new javax.swing.JButton();
        jButtonET = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonTR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNitCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTiendaOrigen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxContenido = new javax.swing.JComboBox<>();
        jTextFieldEstadoPedido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxContenido1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBonificacionCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoPedidoRetiro = new javax.swing.JFormattedTextField();
        jTextFieldMontoDePago = new javax.swing.JTextField();
        jButtonBuscarPedidoRetiro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFaltante = new javax.swing.JTextField();
        jButtonFinalizarVenta = new javax.swing.JButton();
        jLabelDescripcionCodigo = new javax.swing.JLabel();
        jTextFieldEstadoAntesDeSalir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonLimpiarBusqueda1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxDias = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(995, 509));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("RECEPCION DE PEDIDO"));

        jLabel1.setText("Codigo de pedido:");

        jButtonBuscarPedido.setText("Buscar");
        jButtonBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPedidoActionPerformed(evt);
            }
        });

        jButtonLimpiarBusqueda.setText("Limpiar Busqueda");
        jButtonLimpiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarBusquedaActionPerformed(evt);
            }
        });

        jButtonET.setText("ET");
        jButtonET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonETActionPerformed(evt);
            }
        });

        jButtonT.setText("T");
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTActionPerformed(evt);
            }
        });

        jButtonTR.setText("TR");
        jButtonTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTRActionPerformed(evt);
            }
        });

        jLabel4.setText("Nit cliente:");

        jTextFieldNitCliente.setEditable(false);

        jLabel5.setText("Tienda Origen:");

        jTextFieldTiendaOrigen.setEditable(false);

        jLabel7.setText("Contenido:");

        jTextFieldEstadoPedido.setEditable(false);

        jLabel6.setText("Estado Pedido:");

        jLabel17.setText("Establecer estado:");

        jLabel2.setText("INFORMACION DEL PEDIDO (SOLO VISUALIZACION)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButtonBuscarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonLimpiarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonET, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonTR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldTiendaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPedido)
                    .addComponent(jButtonLimpiarBusqueda))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonET)
                        .addComponent(jButtonT)
                        .addComponent(jButtonTR)))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTiendaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("RETIRO DE PEDIDO"));

        jLabel13.setText("Bonificacion al Cliente");

        jTextFieldBonificacionCliente.setEditable(false);
        jTextFieldBonificacionCliente.setText("0.00");

        jLabel14.setText("NIT:");

        jTextFieldNit.setEditable(false);

        jLabel8.setText("Codigo de pedido:");

        jLabel16.setText("Monto de  Pago:");

        jTextFieldMontoDePago.setEditable(false);

        jButtonBuscarPedidoRetiro.setText("Buscar");
        jButtonBuscarPedidoRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPedidoRetiroActionPerformed(evt);
            }
        });

        jLabel9.setText("Faltante a pagar:");

        jTextFieldFaltante.setEditable(false);

        jButtonFinalizarVenta.setText("Finalizar venta");
        jButtonFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarVentaActionPerformed(evt);
            }
        });

        jLabelDescripcionCodigo.setText("No seleccionado ningun pedido");

        jTextFieldEstadoAntesDeSalir.setEditable(false);

        jLabel12.setText("Estado Pedido:");

        jLabel11.setText("Contenido:");

        jButtonLimpiarBusqueda1.setText("Limpiar Busqueda");
        jButtonLimpiarBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarBusqueda1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("FECHA"));

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2020" }));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBoxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(318, 318, 318))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(116, 116, 116)
                                .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMontoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBonificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(229, 229, 229))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButtonBuscarPedidoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButtonLimpiarBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelDescripcionCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEstadoAntesDeSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCodigoPedidoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxContenido1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jFormattedTextFieldCodigoPedidoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarPedidoRetiro)
                            .addComponent(jButtonLimpiarBusqueda1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldEstadoAntesDeSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescripcionCodigo)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBonificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel13))
                    .addComponent(jTextFieldFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxContenido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldMontoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinalizarVenta))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(738, 738, 738)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
        // TODO add your handling code here:
        cambiarEstadoPaquete("T");
    }//GEN-LAST:event_jButtonTActionPerformed

    private void jButtonBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPedidoActionPerformed
        // TODO add your handling code here:
        
        try {
            String codigoPedido = jFormattedTextFieldCodigoPedido.getText();
        
        
            ArrayList<String> datosPedido = new ArrayList<String>();
            datosPedido= this.consultaDB.estadoPedido(codigoPedido,this.baseDeDatos);

            String codigoTienda = datosPedido.get(8);

            if(tiendaSeleccionada.equals(codigoTienda)){
                ArrayList<String> contenido = new ArrayList<String>();
                contenido = consultaDB.productoDeUnPedido(codigoPedido,this.baseDeDatos);
                jComboBoxContenido.removeAllItems();
                for (int i = 0; i < contenido.size(); i++) {
                    jComboBoxContenido.addItem(contenido.get(i));
                }
                this.jTextFieldNitCliente.setText(datosPedido.get(5));
                this.jTextFieldTiendaOrigen.setText(datosPedido.get(7));
                this.jTextFieldEstadoPedido.setText(datosPedido.get(4));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "El pedido que seleciono no llegara a esta tienda");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No existe un pedido con este codigo");
            limpiarCampos2();
        }
        
        
        
    }//GEN-LAST:event_jButtonBuscarPedidoActionPerformed

    private void jButtonETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonETActionPerformed
        // TODO add your handling code here:
        cambiarEstadoPaquete("ET");
    }//GEN-LAST:event_jButtonETActionPerformed

    private void jButtonTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTRActionPerformed
        // TODO add your handling code here:
        cambiarEstadoPaquete("TR");
    }//GEN-LAST:event_jButtonTRActionPerformed

    private void jButtonBuscarPedidoRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPedidoRetiroActionPerformed
        // TODO add your handling code here:
        try {
            String codigoPedidoRetiro = jFormattedTextFieldCodigoPedidoRetiro.getText();
            ArrayList<String> contenido = new ArrayList<String>();
            contenido = consultaDB.estadoPedido(codigoPedidoRetiro,this.baseDeDatos);
            double anticipoIndividual = Double.parseDouble(contenido.get(2));

            int cantidad =this.consultaDB.contarPedidos(codigoPedidoRetiro,this.baseDeDatos);

            double total = this.consultaDB.sumaTotalPedido(codigoPedidoRetiro,this.baseDeDatos);
            double anticipo = this.consultaDB.sumaAnticipoPedido(codigoPedidoRetiro,this.baseDeDatos);

            double anticipoParaTransaccion=0;

            String codigoTienda = contenido.get(8);

            if(tiendaSeleccionada.equals(codigoTienda)){

                ArrayList<String> pedidos = new ArrayList<String>();
                pedidos = consultaDB.productoDeUnPedido(codigoPedidoRetiro,this.baseDeDatos);

                String estadoPaquete = contenido.get(4);
                if(estadoPaquete.equals("entregado")){
                    JOptionPane.showMessageDialog(this, "Este paquete ya fue entregado");
                }
                else
                {
                    jComboBoxContenido1.removeAllItems();
                    for (int i = 0; i < pedidos.size(); i++) {
                        jComboBoxContenido1.addItem(pedidos.get(i));
                    }

                    try {
                        if(anticipoIndividual==(anticipo/cantidad)){
                            jTextFieldFaltante.setText(String.valueOf(total-(anticipo/cantidad)));
                            anticipoParaTransaccion=anticipo/cantidad;
                        }
                        else
                        {
                            jTextFieldFaltante.setText(String.valueOf(total-(anticipo)));
                            anticipoParaTransaccion=anticipo;
                        }
                    } catch (Exception e) {
                    }

                    String estadoPedido = contenido.get(4);
                    jTextFieldEstadoAntesDeSalir.setText(estadoPedido);
                    if(estadoPedido.equals("ET")){
                        jButtonFinalizarVenta.setEnabled(false);
                        jLabelDescripcionCodigo.setText("Pedido en transito");
                    }
                    if(estadoPedido.equals("T")){
                        jButtonFinalizarVenta.setEnabled(true);
                        jLabelDescripcionCodigo.setText("Ya puede retirar el pedido");
                    }
                    if(estadoPedido.equals("TR")){
                        jButtonFinalizarVenta.setEnabled(true);
                        jLabelDescripcionCodigo.setText("El pedido llego con retraso");
                    if(anticipoParaTransaccion==total){
                        jTextFieldBonificacionCliente.setText(String.valueOf(total*0.05));
                    }
                    else{
                            jTextFieldBonificacionCliente.setText(String.valueOf(total*0.02));
                    }
                    }
                        jTextFieldNit.setText(contenido.get(5));
                        jTextFieldMontoDePago.setText(jTextFieldFaltante.getText());
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "El pedido no esta en esta tienda");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No existe un pedido con este codigo");
            limpiarCampos();
        }
    }//GEN-LAST:event_jButtonBuscarPedidoRetiroActionPerformed

    private void jButtonFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarVentaActionPerformed
        // TODO add your handling code here:
        String año = jComboBoxYear.getSelectedItem().toString();
        String mes = jComboBoxMes.getSelectedItem().toString();
        String dia = jComboBoxDias.getSelectedItem().toString();
        String codidoPedido = jFormattedTextFieldCodigoPedidoRetiro.getText();
        
        if(año.equals("Año")&&mes.equals("Mes")&&dia.equals("Dia")){
            JOptionPane.showMessageDialog(this, "No ah seleccionado fecha para realizar la transaccion");
        }else{
            if(jTextFieldEstadoAntesDeSalir.getText().equals("")){
                JOptionPane.showMessageDialog(this, "No ah seleccionado ningun pedido para salida");
            }
            else
            {
                ArrayList<Pedido> pedidos = new ArrayList<Pedido>();
                pedidos = this.consultaDB.retornoDePedidos(codidoPedido,this.baseDeDatos);
                this.modificarDB.modificacionEstadoPedido(codidoPedido, "entregado",this.baseDeDatos);
                String fechaVenta = año+"-"+mes+"-"+dia;
                
                for(int i=0; i<pedidos.size();i++){
                    String res = this.registrarEnDB.registroVenta(new Ventas(pedidos.get(i).getProducto(),pedidos.get(i).getTienda2(),pedidos.get(i).getCliente(),pedidos.get(i).getCantidad(),fechaVenta),this.baseDeDatos);
                    if(!(res.equals(""))){
                        JOptionPane.showMessageDialog(this, res);
                    }
                }
                bonificacionCliente(pedidos.get(0).getCliente(), jTextFieldBonificacionCliente.getText());
                JOptionPane.showMessageDialog(this, "La transaccion se ha completado");
                limpiarCampos();
            }
            
        }
    }//GEN-LAST:event_jButtonFinalizarVentaActionPerformed
    /**
     * Calcula la bonificacion si un paquete llegar tarde a la tienda y lo recoje el cliente asgignado
     * @param nit
     * @param bonificacion
     */
    private void bonificacionCliente(String nit,String bonificacion){
        double bono =0;
        try {
            bono=Double.valueOf(bonificacion);
        } catch (Exception e) {
        }
        double credito = Double.valueOf(this.consultaDB.datosCliente(nit,this.baseDeDatos).get(2));
        double creditoNuevo = credito+bono;
        System.out.println(this.modificarDB.modificarCreditoCliente(nit, String.valueOf(creditoNuevo),this.baseDeDatos));
    }
    private void jButtonLimpiarBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarBusqueda1ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jButtonLimpiarBusqueda1ActionPerformed

    private void jButtonLimpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarBusquedaActionPerformed
        // TODO add your handling code here:
        limpiarCampos2();
    }//GEN-LAST:event_jButtonLimpiarBusquedaActionPerformed
    /**
     * Elimina el texo de los campos de entrada
     */
    private void limpiarCampos2(){
        jFormattedTextFieldCodigoPedido.setText("");
        jTextFieldNitCliente.setText("");
        jTextFieldTiendaOrigen.setText("");
        jComboBoxContenido.removeAllItems();
        jTextFieldEstadoPedido.setText("");
    }
    /**
     * Elimina el texto de los campos de entrada
     */
    private void limpiarCampos(){
        jFormattedTextFieldCodigoPedidoRetiro.setText("");
        jTextFieldEstadoAntesDeSalir.setText("");
        jTextFieldFaltante.setText("0");
        jComboBoxContenido1.removeAllItems();
        jTextFieldNit.setText("");
        jTextFieldMontoDePago.setText("0");
    }
    /**
     * Cambia el estado de los paquetes en el traslado de tiendas
     */
    private void cambiarEstadoPaquete(String estadoNuevo){
        String estadoPaquete = this.jTextFieldEstadoPedido.getText();
        if(estadoPaquete.equals("entregado")){
            JOptionPane.showMessageDialog(this, "Este paquete ya fue entregado no se puede modificar");
        }
        else{
            int respuesta = JOptionPane.showConfirmDialog(this, "Desea cambiar el estado del paquete");
            if(respuesta == JOptionPane.OK_OPTION){
                this.modificarDB.modificacionEstadoPedido(this.jFormattedTextFieldCodigoPedido.getText(), estadoNuevo,this.baseDeDatos);
                JOptionPane.showMessageDialog(this, "Ha cambiado el estado del pedido");
            }
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarPedido;
    private javax.swing.JButton jButtonBuscarPedidoRetiro;
    private javax.swing.JButton jButtonET;
    private javax.swing.JButton jButtonFinalizarVenta;
    private javax.swing.JButton jButtonLimpiarBusqueda;
    private javax.swing.JButton jButtonLimpiarBusqueda1;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonTR;
    private javax.swing.JComboBox<String> jComboBoxContenido;
    private javax.swing.JComboBox<String> jComboBoxContenido1;
    private javax.swing.JComboBox<String> jComboBoxDias;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoPedido;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoPedidoRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescripcionCodigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldBonificacionCliente;
    private javax.swing.JTextField jTextFieldEstadoAntesDeSalir;
    private javax.swing.JTextField jTextFieldEstadoPedido;
    private javax.swing.JTextField jTextFieldFaltante;
    private javax.swing.JTextField jTextFieldMontoDePago;
    private javax.swing.JTextField jTextFieldNit;
    private javax.swing.JTextField jTextFieldNitCliente;
    private javax.swing.JTextField jTextFieldTiendaOrigen;
    // End of variables declaration//GEN-END:variables
}
