/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author benjamin
 */
public class LogInFrame extends javax.swing.JFrame {
    private PrincipalFrame principal;
    /**
     * Creates new form LogInFrame
     */
    public LogInFrame(PrincipalFrame principal) {
        super("Iniciar Sesion");
        initComponents();
        ProfileComponents();
        this.principal=principal;
        this.setBounds(0, 0, 655, 170);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldPassword = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldUsuario = new javax.swing.JFormattedTextField();
        jButtonLog = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(650, 150));
        getContentPane().setLayout(null);

        jLabel2.setText("Nombre De Usuario: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 40, 120, 14);
        getContentPane().add(jFormattedTextFieldPassword);
        jFormattedTextFieldPassword.setBounds(290, 70, 173, 20);

        jLabel3.setText("Contraseña: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 70, 120, 14);
        getContentPane().add(jFormattedTextFieldUsuario);
        jFormattedTextFieldUsuario.setBounds(290, 40, 173, 20);

        jButtonLog.setText("Iniciar");
        getContentPane().add(jButtonLog);
        jButtonLog.setBounds(520, 30, 100, 30);

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar);
        jButtonRegresar.setBounds(520, 70, 100, 30);
        getContentPane().add(jLabelImagen);
        jLabelImagen.setBounds(20, 20, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        this.principal.AccesoDeUsuario(false);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed
    private void ProfileComponents(){
        ImageIcon imagen = new ImageIcon(getClass().getClassLoader().getResource("index.png"));
        jLabelImagen.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPassword;
    private javax.swing.JFormattedTextField jFormattedTextFieldUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables
}
