/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import com.carlos.DBSuport.ConexionDB;
import com.carlos.DBSuport.ConsultasDB;
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author benjamin
 */
public class RastreoPedidoJDialog extends javax.swing.JDialog {
    private Connection baseDeDatos;
    /**
     * Formulario apartado para el rastreo e informacion de un pedido mediante codigo de pedido del mismo
     * @param parent
     * @param modal
     * @param conexionBaseDatos
     */
    public RastreoPedidoJDialog(java.awt.Frame parent, boolean modal,Connection conexionBaseDatos) {
        super(parent, modal);
        this.baseDeDatos=conexionBaseDatos;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("RASTREO DE PEDIDO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoPedido = new javax.swing.JFormattedTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEstadoPedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAnticipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPagoParaRecoger = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLLegada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldOrigen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProductos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo del Pedido");

        jFormattedTextFieldCodigoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCodigoPedidoActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado pedido:");

        jTextFieldEstadoPedido.setEditable(false);

        jLabel3.setText("Producto dentro del pedido");

        jLabel4.setText("Total del pedido:");

        jTextFieldTotal.setEditable(false);

        jLabel5.setText("Anticipo realizado:");

        jTextFieldAnticipo.setEditable(false);

        jLabel6.setText("Pago para recoger:");

        jTextFieldPagoParaRecoger.setEditable(false);

        jLabel7.setText("Tienda de recepcion:");

        jTextFieldLLegada.setEditable(false);

        jLabel8.setText("Tienda de origen:");

        jTextFieldOrigen.setEditable(false);

        jLabel9.setText("DATOS DEL PEDIDO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPagoParaRecoger, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPagoParaRecoger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String codigoPedido = "";
        codigoPedido = this.jFormattedTextFieldCodigoPedido.getText();
        ConsultasDB consultaDePedido = new ConsultasDB();
        ArrayList<String> productos = new ArrayList<String>();
        ArrayList<String> datoPedidos = new ArrayList<String>();
        productos = consultaDePedido.productoDeUnPedido(codigoPedido,this.baseDeDatos);
        datoPedidos=consultaDePedido.estadoPedido(codigoPedido, this.baseDeDatos);
        float totalPedido = consultaDePedido.sumaTotalPedido(codigoPedido,this.baseDeDatos);
        float anticipo = Float.valueOf(datoPedidos.get(2));
        float sumaTotalAnticipo = consultaDePedido.sumaAnticipoPedido(codigoPedido, this.baseDeDatos);
        int cantidad =consultaDePedido.contarPedidos(codigoPedido,this.baseDeDatos);
        try {
            if(anticipo==(sumaTotalAnticipo/cantidad)){
                this.jTextFieldPagoParaRecoger.setText(String.valueOf(totalPedido-(sumaTotalAnticipo/cantidad)));
                this.jTextFieldAnticipo.setText(String.valueOf((sumaTotalAnticipo/cantidad)));
            }
            else
            {
                this.jTextFieldPagoParaRecoger.setText(String.valueOf(totalPedido-(sumaTotalAnticipo)));
                this.jTextFieldAnticipo.setText(String.valueOf((sumaTotalAnticipo)));
            }
        } catch (Exception e) {
        }
        jComboBoxProductos.removeAllItems();
        for (int i = 0; i < productos.size(); i++) {
            jComboBoxProductos.addItem(productos.get(i));
        }
        //Oras caracteristicas de los paquetes
        this.jTextFieldEstadoPedido.setText(datoPedidos.get(4));
        this.jTextFieldOrigen.setText(datoPedidos.get(7));
        this.jTextFieldLLegada.setText(datoPedidos.get(8));
        this.jTextFieldTotal.setText(String.valueOf(totalPedido));
        
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jFormattedTextFieldCodigoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodigoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCodigoPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxProductos;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAnticipo;
    private javax.swing.JTextField jTextFieldEstadoPedido;
    private javax.swing.JTextField jTextFieldLLegada;
    private javax.swing.JTextField jTextFieldOrigen;
    private javax.swing.JTextField jTextFieldPagoParaRecoger;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
