/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import com.carlos.DBSuport.ConexionDB;
import com.carlos.DBSuport.ConsultasDB;
import com.carlos.DBSuport.ModificacionesDB;
import com.carlos.DBSuport.RegistroDB;
import com.carlos.Entities.Client;
import com.carlos.Entities.Pedido;
import com.carlos.Entities.Product;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class RealizarPedidoJDialog extends javax.swing.JDialog {
    
    private Connection baseDeDatos;
    private ConsultasDB consultas = new ConsultasDB();
    private RegistroDB registrar = new RegistroDB();
    private String codigoTiendaConSeccion;
    private ModificacionesDB modificarDatos = new ModificacionesDB();
    /**
     * Formaulario en el cual se hace un pedido introduciendo los datos de lo que se quiere solicitar
     * @param parent
     * @param modal
     * @param nombreTienda
     * @param conexionBaseDatos
     */
    public RealizarPedidoJDialog(java.awt.Frame parent, boolean modal,String nombreTienda,Connection conexionBaseDatos) {
        super(parent, modal);
        this.baseDeDatos=conexionBaseDatos;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("REALIZAR PEDIDO");
        codigoTiendaConSeccion=consultas.codigoTienda(nombreTienda,this.baseDeDatos);
        listarTiendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxDias = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxTiendas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoDelProducto = new javax.swing.JFormattedTextField();
        jButtonBuscarProducto = new javax.swing.JButton();
        jButtonLimpiarBusquedaProducto = new javax.swing.JButton();
        jFormattedTextFieldExistenciaDelProducto = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNIT = new javax.swing.JLabel();
        jFormattedTextFieldNIT = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNombreCliente1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldCreditoDisponible = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextFieldPrecioDelProducto = new javax.swing.JFormattedTextField();
        jLabel1CantidadUnidades = new javax.swing.JLabel();
        jComboBoxUnidadeComprar = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldPrecioDelPedido = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldPagoMinimo = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldCreditoAUsar = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldPagoEfectivo = new javax.swing.JFormattedTextField();
        jButtonRealizarTransaccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("FECHA DE PEDIDO"));

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2020" }));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBoxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECCION DE TIENDA"));

        jLabel12.setText("Codigo de tienda:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(45, 45, 45)
                .addComponent(jComboBoxTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECCION DE PRODUCTO"));

        jLabel1.setText("Codigo del Producto:");

        jButtonBuscarProducto.setText("Buscar");
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });

        jButtonLimpiarBusquedaProducto.setText("Limpiar Busqueda");
        jButtonLimpiarBusquedaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarBusquedaProductoActionPerformed(evt);
            }
        });

        jFormattedTextFieldExistenciaDelProducto.setEditable(false);
        jFormattedTextFieldExistenciaDelProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldExistenciaDelProducto.setText("0");

        jLabel13.setText("Existencias:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldCodigoDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldExistenciaDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonLimpiarBusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCodigoDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jFormattedTextFieldExistenciaDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonLimpiarBusquedaProducto))
                .addGap(14, 14, 14))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE FACTURACION"));
        jPanel4.setToolTipText("");

        jLabelNIT.setText("NIT:");

        jFormattedTextFieldNombreCliente1.setEditable(false);

        jLabel4.setText("Nombre:");

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar Busqueda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Credito:");

        jFormattedTextFieldCreditoDisponible.setEditable(false);
        jFormattedTextFieldCreditoDisponible.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldCreditoDisponible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldCreditoDisponible.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(jFormattedTextFieldCreditoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelNIT)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldNombreCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNIT)
                    .addComponent(jButtonBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldNombreCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldCreditoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("CONFIRMACION DE PEDIDO"));

        jLabel14.setText("Precio del Producto:");

        jFormattedTextFieldPrecioDelProducto.setEditable(false);
        jFormattedTextFieldPrecioDelProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPrecioDelProducto.setText("0.00");

        jLabel1CantidadUnidades.setText("Cantidad de Unidades:");

        jComboBoxUnidadeComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jComboBoxUnidadeComprar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUnidadeComprarItemStateChanged(evt);
            }
        });

        jLabel7.setText("Precio del Pedido:");

        jFormattedTextFieldPrecioDelPedido.setEditable(false);
        jFormattedTextFieldPrecioDelPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPrecioDelPedido.setText("0");

        jLabel8.setText("25% a Pagar minimo: ");

        jFormattedTextFieldPagoMinimo.setEditable(false);
        jFormattedTextFieldPagoMinimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPagoMinimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPagoMinimo.setText("0");

        jLabel9.setText("Credito a usar:");

        jFormattedTextFieldCreditoAUsar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldCreditoAUsar.setText("0");

        jLabel10.setText("Aportacion en Efectivo:");

        jFormattedTextFieldPagoEfectivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPagoEfectivo.setText("0");

        jButtonRealizarTransaccion.setText("Realizar Transaccion");
        jButtonRealizarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarTransaccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldPrecioDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1CantidadUnidades))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldPrecioDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUnidadeComprar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldPagoMinimo))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(59, 59, 59)
                                .addComponent(jFormattedTextFieldCreditoAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButtonRealizarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextFieldPrecioDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1CantidadUnidades)
                    .addComponent(jComboBoxUnidadeComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldPrecioDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldPagoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldCreditoAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jFormattedTextFieldPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonRealizarTransaccion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarTransaccionActionPerformed
        // TODO add your handling code here:
        String codigoProducto = this.jFormattedTextFieldCodigoDelProducto.getText();
        String NIT = this.jFormattedTextFieldNIT.getText();
        String nombreCliente = this.jFormattedTextFieldExistenciaDelProducto.getText();
        String codigoTienda = this.jComboBoxTiendas.getSelectedItem().toString();
        double precioProducto=0;
        double pagoEfectivo=0;
        double usoCredito=0;
        double creditoDisponible=0;
        double pagoMinimo=0;
        int unidadesAcomprar=0;
        //Se realizan las conversiones necesarias para aceptar los datos de entrada
        try {
            precioProducto = Double.parseDouble(jFormattedTextFieldPrecioDelPedido.getText());
            pagoEfectivo = Double.parseDouble(jFormattedTextFieldPagoEfectivo.getText());
            usoCredito = Double.parseDouble(jFormattedTextFieldCreditoAUsar.getText());
            creditoDisponible = Double.parseDouble(jFormattedTextFieldCreditoDisponible.getText());
            pagoMinimo = Double.parseDouble(jFormattedTextFieldPagoMinimo.getText());
            unidadesAcomprar = Integer.parseInt(jComboBoxUnidadeComprar.getSelectedItem().toString());
            
        } catch (Exception e) {
        }
        //Se comprueban los datos de entrada en para verficar que se haya seleccionado un producto
        if(!(codigoProducto.equals("")||precioProducto==0)){
            //verifica la disponibilidad del producto
            if(!(consultas.datosExistenciaProducto(codigoProducto, codigoTienda,this.baseDeDatos).endsWith("0"))){
                //Verifica que hayan los datos disponibles del cliente 
                if(!(nombreCliente.equals("")||NIT.equals(""))){
                    //verifica que el credito a utilizar sea una cantiad real
                    if(usoCredito>=0)
                    {
                        //Verifica el credito a utilizar en la compra
                        if(!(usoCredito>creditoDisponible)){
                            //Verifica que el pago total de la compra cumpla el minimo requerido
                            if(!((pagoEfectivo+usoCredito)<pagoMinimo)){
                                if((pagoEfectivo+usoCredito)>pagoMinimo){
                                    int respuesta = JOptionPane.showConfirmDialog(this, "Desea pagar mas del 25% minimo");
                                    if(respuesta==JOptionPane.YES_OPTION){
                                        ejecutarPedido();
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(this, "Configure los pagos nuevamente\nNo se realizara la transaccion");
                                    }
                                }
                                else{
                                    //Acciones del pedido
                                    ejecutarPedido();
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this, "El pago no cumple el minimo de 25%\nNo se realizara la transaccion");
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "El credito del a usar supera el diponible\nNo se realizara la transaccion");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "El credito a usar no es correcto\nNo se realizara la transaccion");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No a asignado el cliente\nNo se realizara la transaccion");
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, "No hay existencia del producto en la tienda seleccionada\nNo se realizara la transaccion");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No a seleccionado ningun producto\nNo se realizara la transaccion");
        }
    }//GEN-LAST:event_jButtonRealizarTransaccionActionPerformed
    /**
     * Realiza la creacion del objeto pedido y lo introduce en la base de datos
     */
    private void ejecutarPedido(){
        String year = jComboBoxYear.getSelectedItem().toString();
        String mes = jComboBoxMes.getSelectedItem().toString();
        String dia = jComboBoxDias.getSelectedItem().toString();
        if((year.equals("Año"))&&(mes.equals("Mes"))&&(dia.equals("Dia"))){
            JOptionPane.showMessageDialog(this, "No a asignado una fecha a la transaccion");
        }
        else{
            //Variables para inicializar un pedido
            String fecha = year+"-"+mes+"-"+dia;
            String codigoPedido = "";
            String tiendaOrigen = jComboBoxTiendas.getSelectedItem().toString();
            String tiendaLlegada = this.codigoTiendaConSeccion;
            String cliente = jFormattedTextFieldNIT.getText();
            String producto = jFormattedTextFieldCodigoDelProducto.getText();
            int cantidad = Integer.valueOf(jComboBoxUnidadeComprar.getSelectedItem().toString());
            double total = Double.valueOf(jFormattedTextFieldPrecioDelPedido.getText());
            double efectivo = Double.valueOf(jFormattedTextFieldPagoEfectivo.getText());
            double credito = Double.valueOf(jFormattedTextFieldCreditoAUsar.getText());
            double anticipo = efectivo+credito;
            //Generacion del codigo de pedido del cliente
            codigoPedido=year+mes+dia+cliente;
            Pedido pedidoNuevo = new Pedido(codigoPedido, tiendaOrigen, tiendaLlegada, fecha, cliente, producto, cantidad, total, anticipo);
            //respuesta por si ocurre un error en el momento d ejcucion en la base de datos
            String respuesta = this.registrar.registroPedido(pedidoNuevo,this.baseDeDatos);
            if(!(respuesta.equals(""))){
                JOptionPane.showMessageDialog(this, respuesta);
            }
            else{
                JOptionPane.showMessageDialog(this, "Se ha registrado correctamente el pedido");
                descontarTienda();
                descontarCliente();
            }
            
        }
    }
    /**
     * Descuenta las existencia pedidadas de un producto en la tienda que lo expende
     */
    private void descontarTienda(){
        int cantidadVendida = Integer.valueOf(jComboBoxUnidadeComprar.getSelectedItem().toString());
        int cantidadOriginarl = Integer.valueOf(jFormattedTextFieldExistenciaDelProducto.getText());
        String codigoTienda = jComboBoxTiendas.getSelectedItem().toString();
        int nuevaCantidad = cantidadOriginarl-cantidadVendida;
        String codigoProducto = jFormattedTextFieldCodigoDelProducto.getText();
        Product productoModificar = new Product("", "", codigoProducto, nuevaCantidad, 0, "", 0, codigoTienda);
        this.modificarDatos.modificarExistencia(productoModificar,this.baseDeDatos);
    }
    /**
     * Descuenta la cantidad de credito del cliente si tuviera
     */
    private void descontarCliente(){
        String nitCliente = jFormattedTextFieldNIT.getText();
        double creditoDiponible = Double.valueOf(jFormattedTextFieldCreditoDisponible.getText());
        double creditoUsado = Double.valueOf(jFormattedTextFieldCreditoAUsar.getText());
        double nuevoCredito = creditoDiponible-creditoUsado;
        this.modificarDatos.modificarCreditoCliente(nitCliente, String.valueOf(nuevoCredito),this.baseDeDatos);
    }
    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        
        String cliente = this.jFormattedTextFieldNIT.getText();
        if(!(cliente.equals("")))
        {
            this.jFormattedTextFieldNIT.setEditable(false);
            ArrayList<String> nombreCliente = new ArrayList<String>();
            nombreCliente = consultas.datosCliente(cliente,this.baseDeDatos);
            jFormattedTextFieldNombreCliente1.setText(nombreCliente.get(0));
            jFormattedTextFieldCreditoDisponible.setText(nombreCliente.get(2));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No a introducido los datos del cliente");
        }
        
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        // TODO add your handling code here:
       
        
        String codigoProducto = this.jFormattedTextFieldCodigoDelProducto.getText();
        String codigoTienda = this.jComboBoxTiendas.getSelectedItem().toString();
        
        if(this.codigoTiendaConSeccion.equals(codigoTienda)){
            JOptionPane.showMessageDialog(this, "No puede seleccionar la misma tienda");
        }
        else
        {
            if(!(codigoProducto.equals("")||codigoTienda.equals("")))
            {
                //Desabilitar campos de configuracion busqueda de producto
                this.jComboBoxTiendas.setEnabled(false);
                this.jFormattedTextFieldCodigoDelProducto.setEnabled(false);

                jFormattedTextFieldExistenciaDelProducto.setText(consultas.datosExistenciaProducto(codigoProducto, codigoTienda,this.baseDeDatos));
                if(!(jFormattedTextFieldExistenciaDelProducto.getText().equals("0")))
                {
                    jComboBoxUnidadeComprar.removeAllItems();
                    try {
                        long disponivilidad = Long.parseLong(jFormattedTextFieldExistenciaDelProducto.getText());
                        for (int i = 1; i <= disponivilidad; i++) {
                        jComboBoxUnidadeComprar.addItem(String.valueOf(i));
                    }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "No hay existencias del producto ingresado");
                    }
                    
                    //Mostrar los atributos del producto
                    ArrayList<String> datosProducto = new ArrayList<String>();
                    datosProducto=consultas.datosProducto(codigoProducto,this.baseDeDatos);
                    jFormattedTextFieldPrecioDelProducto.setText(datosProducto.get(2));
                    calculosDeCosto();
                }
                else
                {
                    jComboBoxUnidadeComprar.removeAllItems();
                    jComboBoxUnidadeComprar.addItem(String.valueOf(0));
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No a colocado los campos de busqueda del producto");
            }
        }
        
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed
    /**
     * Realiza los calculos del costo mediante la cantidad y el precio
     */
    private void calculosDeCosto(){
        try{
        double precioProducto = Double.valueOf(jFormattedTextFieldPrecioDelProducto.getText());
        long cantidadDeUnidades = Long.valueOf(jComboBoxUnidadeComprar.getSelectedItem().toString());
        
        double costoPedido = Double.valueOf(precioProducto*cantidadDeUnidades);
        double pagoMinimo = Double.valueOf(costoPedido*(0.25));
        
        jFormattedTextFieldPagoMinimo.setText(String.valueOf(pagoMinimo));
        jFormattedTextFieldPrecioDelPedido.setText(String.valueOf(costoPedido));
        }catch(Exception e){
            
        }
        
        
    }
    private void jButtonLimpiarBusquedaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarBusquedaProductoActionPerformed
        // TODO add your handling code here:
        this.jComboBoxTiendas.setEnabled(true);
        this.jFormattedTextFieldCodigoDelProducto.setEnabled(true);
        
        this.jComboBoxTiendas.setSelectedIndex(0);
        this.jFormattedTextFieldCodigoDelProducto.setText("");
        this.jFormattedTextFieldExistenciaDelProducto.setText("0");
        
        this.jFormattedTextFieldPrecioDelPedido.setText("0.00");
        this.jFormattedTextFieldPagoMinimo.setText("0.00");
        
        jComboBoxUnidadeComprar.removeAllItems();
        jComboBoxUnidadeComprar.addItem(String.valueOf(0));
    }//GEN-LAST:event_jButtonLimpiarBusquedaProductoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.jFormattedTextFieldNIT.setEditable(true);
        this.jFormattedTextFieldNIT.setText("");
        this.jFormattedTextFieldNombreCliente1.setText("");
        this.jFormattedTextFieldCreditoDisponible.setText("0");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxUnidadeComprarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUnidadeComprarItemStateChanged
        // TODO add your handling code here:
        calculosDeCosto();
    }//GEN-LAST:event_jComboBoxUnidadeComprarItemStateChanged
    /**
     * Lista los codigos de tiendas que se encuentran en la base de datos
     */
    private void listarTiendas(){
        ArrayList<String> tiendas = new ArrayList<String>();
        tiendas = consultas.codigosDeTiendas(this.baseDeDatos);
        for (int i = 0; i < tiendas.size(); i++) {
            jComboBoxTiendas.addItem(tiendas.get(i));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JButton jButtonLimpiarBusquedaProducto;
    private javax.swing.JButton jButtonRealizarTransaccion;
    private javax.swing.JComboBox<String> jComboBoxDias;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxTiendas;
    private javax.swing.JComboBox<String> jComboBoxUnidadeComprar;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoDelProducto;
    private javax.swing.JFormattedTextField jFormattedTextFieldCreditoAUsar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCreditoDisponible;
    private javax.swing.JFormattedTextField jFormattedTextFieldExistenciaDelProducto;
    private javax.swing.JFormattedTextField jFormattedTextFieldNIT;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombreCliente1;
    private javax.swing.JFormattedTextField jFormattedTextFieldPagoEfectivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPagoMinimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioDelPedido;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioDelProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1CantidadUnidades;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNIT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
