/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class RealizarPedidoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form RealizarPedidoJDialog
     */
    public RealizarPedidoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("REALIZAR PEDIDO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoDelProducto = new javax.swing.JFormattedTextField();
        jButtonBuscarProducto = new javax.swing.JButton();
        jLabelNIT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldExistenciaDelProducto = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCreditoAUsar = new javax.swing.JFormattedTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldCreditoDisponible = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldPrecioDelPedido = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldPagoMinimo = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldNIT = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPagoEfectivo = new javax.swing.JFormattedTextField();
        jButtonRealizarTransaccion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldNombreCliente1 = new javax.swing.JFormattedTextField();
        jButtonLimpiarBusquedaProducto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1CantidadUnidades = new javax.swing.JLabel();
        jComboBoxUnidadeComprar = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextFieldPrecioDelPedido1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo del Producto:");

        jButtonBuscarProducto.setText("Buscar");
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });

        jLabelNIT.setText("NIT:");

        jLabel2.setText("SELECCION DE PRODUCTO");

        jLabel3.setText("CONFIRMACION DE TRANSACCION");

        jFormattedTextFieldExistenciaDelProducto.setEditable(false);
        jFormattedTextFieldExistenciaDelProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldExistenciaDelProducto.setText("0");

        jLabel4.setText("Nombre:");

        jFormattedTextFieldCreditoAUsar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldCreditoAUsar.setText("0");

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Credito:");

        jFormattedTextFieldCreditoDisponible.setEditable(false);
        jFormattedTextFieldCreditoDisponible.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldCreditoDisponible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldCreditoDisponible.setText("0");

        jLabel6.setText("DATOS DE FACTURACION");

        jLabel7.setText("Precio del Pedido:");

        jFormattedTextFieldPrecioDelPedido.setEditable(false);
        jFormattedTextFieldPrecioDelPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPrecioDelPedido.setText("0");

        jLabel8.setText("25% a Pagar minimo: ");

        jFormattedTextFieldPagoMinimo.setEditable(false);
        jFormattedTextFieldPagoMinimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPagoMinimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPagoMinimo.setText("0");

        jLabel9.setText("Credito a usar:");

        jLabel10.setText("Aportacion en Efectivo:");

        jFormattedTextFieldPagoEfectivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPagoEfectivo.setText("0");

        jButtonRealizarTransaccion.setText("Realizar Transaccion");
        jButtonRealizarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarTransaccionActionPerformed(evt);
            }
        });

        jLabel11.setText("SELECCION DE TIENDA");

        jLabel12.setText("Codigo de tienda:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Existencias:");

        jFormattedTextFieldNombreCliente1.setEditable(false);

        jButtonLimpiarBusquedaProducto.setText("Limpiar Busqueda");
        jButtonLimpiarBusquedaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarBusquedaProductoActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar Busqueda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1CantidadUnidades.setText("Cantidad de Unidades:");

        jComboBoxUnidadeComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jComboBoxUnidadeComprar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUnidadeComprarItemStateChanged(evt);
            }
        });

        jLabel14.setText("Precio del Producto:");

        jFormattedTextFieldPrecioDelPedido1.setEditable(false);
        jFormattedTextFieldPrecioDelPedido1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPrecioDelPedido1.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(45, 45, 45)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(220, 220, 220))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(83, 83, 83)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldCodigoDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldExistenciaDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonLimpiarBusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jButtonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFormattedTextFieldPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldCreditoAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRealizarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(421, 421, 421))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNIT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jFormattedTextFieldNombreCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(38, 38, 38)
                                    .addComponent(jFormattedTextFieldCreditoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel7))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldPrecioDelPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldPrecioDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(29, 29, 29)
                                    .addComponent(jFormattedTextFieldPagoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1CantidadUnidades)
                                    .addGap(31, 31, 31)
                                    .addComponent(jComboBoxUnidadeComprar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCodigoDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProducto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jFormattedTextFieldExistenciaDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiarBusquedaProducto))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNIT)
                    .addComponent(jButtonBuscarCliente)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldCreditoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldNombreCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextFieldPrecioDelPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1CantidadUnidades)
                    .addComponent(jComboBoxUnidadeComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldPrecioDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldPagoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonRealizarTransaccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldCreditoAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jFormattedTextFieldPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarTransaccionActionPerformed
        // TODO add your handling code here:
        String codigoProducto = this.jFormattedTextFieldCodigoDelProducto.getText();
        String NIT = this.jFormattedTextFieldNIT.getText();
        String nombreCliente = this.jFormattedTextFieldExistenciaDelProducto.getText();
        String codigoTienda = this.jComboBox1.getSelectedItem().toString();
        float precioProducto=0;
        float pagoEfectivo=0;
        float usoCredito=0;
        float creditoDisponible=0;
        float pagoMinimo=0;
        int unidadesAcomprar=0;
        //Se realizan las conversiones necesarias para aceptar los datos de entrada
        try {
            precioProducto = Float.parseFloat(jFormattedTextFieldPrecioDelPedido.getText());
            pagoEfectivo = Float.parseFloat(jFormattedTextFieldPagoEfectivo.getText());
            usoCredito = Float.parseFloat(jFormattedTextFieldCreditoAUsar.getText());
            creditoDisponible = Float.parseFloat(jFormattedTextFieldCreditoDisponible.getText());
            pagoMinimo = Float.parseFloat(jFormattedTextFieldPagoMinimo.getText());
            unidadesAcomprar = Integer.parseInt(jComboBoxUnidadeComprar.getSelectedItem().toString());
            
        } catch (Exception e) {
        }
        //Se comprueban los datos de entrada en para verficar que se haya seleccionado un producto
        if(!(codigoProducto.equals("")||precioProducto==0)){
            //verifica la disponibilidad del producto
            if(!(disponibilidadDeProducto(codigoProducto,codigoTienda)==0)){
                //Verifica que hayan los datos disponibles del cliente 
                if(!(nombreCliente.equals("")||NIT.equals(""))){
                    //verifica que el credito a utilizar sea una cantiad real
                    if(usoCredito>=0)
                    {
                        //Verifica el credito a utilizar en la compra
                        if(!(usoCredito>creditoDisponible)){
                            //Verifica que el pago total de la compra cumpla el minimo requerido
                            if(!((pagoEfectivo+usoCredito)<pagoMinimo)){
                                if((pagoEfectivo+usoCredito)>pagoMinimo){
                                    int respuesta = JOptionPane.showConfirmDialog(this, "Desea pagar mas del 25% minimo");
                                    if(respuesta==JOptionPane.YES_OPTION){
                                        
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(this, "Configure los pagos nuevamente\nNo se realizara la transaccion");
                                    }
                                }
                                else{
                                    //Acciones del pedido
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this, "El pago no cumple el minimo de 25%\nNo se realizara la transaccion");
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "El credito del a usar supera el diponible\nNo se realizara la transaccion");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "El credito a usar no es correcto\nNo se realizara la transaccion");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No a asignado el cliente\nNo se realizara la transaccion");
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, "No hay existencia del producto en la tenda seleccionada\nNo se realizara la transaccion");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No a seleccionado ningun producto\nNo se realizara la transaccion");
        }
    }//GEN-LAST:event_jButtonRealizarTransaccionActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        
        String cliente = this.jFormattedTextFieldNIT.getText();
        if(!(cliente.equals("")))
        {
            this.jFormattedTextFieldNIT.setEditable(false);
            //Realizar busqueda del cliente en la base de datos
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No a introducido los datos del cliente");
        }
        
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        // TODO add your handling code here:
        
        
        String codigoProducto = this.jFormattedTextFieldCodigoDelProducto.getText();
        String codigoTienda = this.jComboBox1.getSelectedItem().toString();
        
        if(!(codigoProducto.equals("")||codigoTienda.equals("")))
        {
            //Desabilitar campos de configuracion busqueda de producto
            this.jComboBox1.setEnabled(false);
            this.jFormattedTextFieldCodigoDelProducto.setEnabled(false);
            int diponibilidad = disponibilidadDeProducto(codigoProducto, codigoTienda);
            jFormattedTextFieldExistenciaDelProducto.setText(String.valueOf(diponibilidad));
            if(diponibilidad!=0)
            {
                jComboBoxUnidadeComprar.removeAllItems();
                for (int i = 1; i <= diponibilidad; i++) {
                    jComboBoxUnidadeComprar.addItem(String.valueOf(i));
                }
            }
            else
            {
                jComboBoxUnidadeComprar.removeAllItems();
                jComboBoxUnidadeComprar.addItem(String.valueOf(0));
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No a colocado los campos de busqueda del producto");
        }
        
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jButtonLimpiarBusquedaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarBusquedaProductoActionPerformed
        // TODO add your handling code here:
        this.jComboBox1.setEnabled(true);
        this.jFormattedTextFieldCodigoDelProducto.setEnabled(true);
        
        this.jComboBox1.setSelectedIndex(0);
        this.jFormattedTextFieldCodigoDelProducto.setText("");
        this.jFormattedTextFieldExistenciaDelProducto.setText("0");
        
        this.jFormattedTextFieldPrecioDelPedido.setText("0.00");
        this.jFormattedTextFieldPagoMinimo.setText("0.00");
        
        jComboBoxUnidadeComprar.removeAllItems();
        jComboBoxUnidadeComprar.addItem(String.valueOf(0));
    }//GEN-LAST:event_jButtonLimpiarBusquedaProductoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.jFormattedTextFieldNIT.setEditable(true);
        this.jFormattedTextFieldNIT.setText("");
        this.jFormattedTextFieldNombreCliente1.setText("");
        this.jFormattedTextFieldCreditoDisponible.setText("0");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxUnidadeComprarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUnidadeComprarItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBoxUnidadeComprarItemStateChanged
    private int disponibilidadDeProducto(String codigoProducto,String codigoTienda){
        int cantidad = 0;
        
        return cantidad;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JButton jButtonLimpiarBusquedaProducto;
    private javax.swing.JButton jButtonRealizarTransaccion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxUnidadeComprar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoDelProducto;
    private javax.swing.JFormattedTextField jFormattedTextFieldCreditoAUsar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCreditoDisponible;
    private javax.swing.JFormattedTextField jFormattedTextFieldExistenciaDelProducto;
    private javax.swing.JFormattedTextField jFormattedTextFieldNIT;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombreCliente1;
    private javax.swing.JFormattedTextField jFormattedTextFieldPagoEfectivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPagoMinimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioDelPedido;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioDelPedido1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1CantidadUnidades;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNIT;
    // End of variables declaration//GEN-END:variables
}
