/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.Graphics;

import com.carlos.DBSuport.*;
import com.carlos.Entities.*;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Pac
 */
public class VentaJDialog extends javax.swing.JDialog {
    //Variable bandera del tipo de transaccion de datos
    private boolean tranNorm=true;
    private ModificacionesDB modificacion = new ModificacionesDB();
    private ConsultasDB consulta = new ConsultasDB();
    private RegistroDB registro = new RegistroDB();
    private Connection baseDeDatos ;
    private String tiendaSleccionada;
    private DefaultTableModel modeloDeTabla = new DefaultTableModel();
    private ArrayList<Ventas> ventasAcumuladas = new ArrayList<Ventas>();
    /**
     * Formulario mediante el cual se hacen la ventas de productos del ctaalogo de la empresa
     * @param parent
     * @param modal
     * @param tiendaSleccionada
     * @param conexionBaseDatos
     */
    public VentaJDialog(java.awt.Frame parent, boolean modal,String tiendaSleccionada,Connection conexionBaseDatos) {
        super(parent, modal);
        this.baseDeDatos=conexionBaseDatos;
        this.tiendaSleccionada = this.consulta.codigoTienda(tiendaSleccionada,this.baseDeDatos);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("VENTAS");
        modeloDeTabla = (DefaultTableModel)jTableProductos.getModel();
    }
    
    public VentaJDialog(java.awt.Frame parent, boolean modal, Pedido pedidoProcesar) {
        super(parent, modal);
        initComponents();
        this.tranNorm=false;
        this.setLocationRelativeTo(null);
        this.setTitle("VENTAS");
        
        cargarEspecialDeDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonTransaccion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jFormattedTextFieldPrecio = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCantidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldCodigoProducto = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNombreProducto = new javax.swing.JFormattedTextField();
        jButtonBuscarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCreditoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldNIT = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldNombreCliente = new javax.swing.JFormattedTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxDias = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldUsoCredito = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPagoEfectivo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTotal = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIPCION DE FACTURA"));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonTransaccion.setText("Realizar Transaccion");
        jButtonTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransaccionActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("INTRODUCCION DE PRODUCTO"));

        jFormattedTextFieldPrecio.setEditable(false);
        jFormattedTextFieldPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPrecio.setText("0.00");

        jLabel11.setText("Cantidad:");

        jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));

        jLabel1.setText("Codigo del Producto:");

        jLabel2.setText("Nombre del Producto:");

        jFormattedTextFieldNombreProducto.setEditable(false);

        jButtonBuscarProducto.setText("Buscar Producto");
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio:");

        jButtonIngresar.setText("Ingresarlo");
        jButtonIngresar.setEnabled(false);
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProducto))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIngresar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE FACTURACION"));

        jLabel8.setText("Credito del Cliente:");

        jTextFieldCreditoCliente.setEditable(false);
        jTextFieldCreditoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCreditoCliente.setText("0");

        jLabel5.setText("NIT:");

        jLabel6.setText("Nombre:");

        jFormattedTextFieldNombreCliente.setEditable(false);

        jButtonBuscarCliente.setText("Buscar Cliente");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCreditoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCreditoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("FECHA"));

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2020" }));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBoxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("METODOS DE PAGO"));

        jLabel9.setText("Pago Efectivo:");

        jLabel10.setText("Uso de Credito:");

        jFormattedTextFieldUsoCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldUsoCredito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldUsoCredito.setText("0");

        jFormattedTextFieldPagoEfectivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));
        jFormattedTextFieldPagoEfectivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPagoEfectivo.setToolTipText("");

        jFormattedTextFieldTotal.setEditable(false);
        jFormattedTextFieldTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldTotal.setText("0.00");
        jFormattedTextFieldTotal.setToolTipText("");

        jLabel12.setText("Total:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldUsoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jLabel12)
                .addGap(38, 38, 38)
                .addComponent(jFormattedTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jFormattedTextFieldUsoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonTransaccion)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransaccionActionPerformed
        // TODO add your handling code here:
        //Utiliza el metodo de transaccion de datos
        if(tranNorm)
        {
            transaccionNormal();
        }
        else
        {
            transaccionEspecial();
        }
        
    }//GEN-LAST:event_jButtonTransaccionActionPerformed
    
    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        // TODO add your handling code here:
        String codigoProducto = this.jFormattedTextFieldCodigoProducto.getText();
        String existencia =this.consulta.datosExistenciaProducto(codigoProducto, tiendaSleccionada,this.baseDeDatos);
        if(existencia.equals("0")||existencia.equals("")){
            
            JOptionPane.showMessageDialog(this, "No hay existencia del producto en tienda haga un pedido del mismo en el apartado");
            jComboBoxCantidad.removeAllItems();
        }
        else
        {
            if(codigoProducto.equals("")){
                JOptionPane.showMessageDialog(this, "No ha introducido valores en los campos de busqueda");
            }
            else
            {
                try {
                    ArrayList<String> datosProducto = new ArrayList<String>();
                    datosProducto = this.consulta.datosProducto(codigoProducto,this.baseDeDatos);
                    jFormattedTextFieldNombreProducto.setText(datosProducto.get(0));
                    jFormattedTextFieldPrecio.setText(datosProducto.get(2));
                    jButtonIngresar.setEnabled(true);
                    int cantidad = Integer.valueOf(existencia);
                    jComboBoxCantidad.removeAllItems();
                    for (int i = 1; i <cantidad ; i++) {
                        jComboBoxCantidad.addItem(String.valueOf(i));
                    }
                } catch (Exception e) {
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        String nitCliente = this.jFormattedTextFieldNIT.getText();
        ArrayList<String> datosCliente = new ArrayList<String>();
        datosCliente = this.consulta.datosCliente(nitCliente,this.baseDeDatos);
        try {
            jFormattedTextFieldNombreCliente.setText(datosCliente.get(0));
            jTextFieldCreditoCliente.setText(datosCliente.get(2));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        this.jFormattedTextFieldNIT.setEditable(false);
        String year = jComboBoxYear.getSelectedItem().toString();
        String Mes = jComboBoxMes.getSelectedItem().toString();
        String Dia = jComboBoxDias.getSelectedItem().toString();
        if(!year.equals("Año")&&!Mes.equals("Mes")&&!Dia.equals("Dia")){
            if(!(jFormattedTextFieldNombreCliente.getText().equals(""))){
                double precioParcial=0;
                int cantidad=1;
                Object[] productos = new Object[4];

                cantidad = Integer.valueOf(jComboBoxCantidad.getSelectedItem().toString());
                precioParcial = precioParcial + ((Double.valueOf(jFormattedTextFieldPrecio.getText()))*cantidad);

                productos[0]=jFormattedTextFieldNombreProducto.getText();
                productos[1]=jFormattedTextFieldCodigoProducto.getText();
                productos[2]=jComboBoxCantidad.getSelectedItem().toString();
                productos[3]=String.valueOf(precioParcial);
                String fecha = year+"-"+Mes+"-"+Dia;
                
                ventasAcumuladas.add(new Ventas(jFormattedTextFieldCodigoProducto.getText(), tiendaSleccionada,jFormattedTextFieldNIT.getText(),cantidad, fecha));

                modeloDeTabla.addRow(productos);
                jButtonIngresar.setEnabled(false);
                DecimalFormat formato1 = new DecimalFormat("#.00");
                jFormattedTextFieldTotal.setText(String.valueOf(formato1.format(precioParcial)));
                
                jComboBoxYear.setEditable(false);
                jComboBoxMes.setEditable(false);
                jComboBoxDias.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Debe de ingresar los datos del cliente");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Marque una fecha para la transaccion");
        }
        
        
    }//GEN-LAST:event_jButtonIngresarActionPerformed
    /**
     * Transaccion normal de un producto
     */
    private void transaccionNormal(){
        double creditoCliente=0;
        double pagoEfectivo =0;
        double usoCredito=0;
        double precio=0;
        //Extraccion de informacion del formulario
        String codigoProducto = this.jFormattedTextFieldCodigoProducto.getText();
        String NombreProducto = this.jFormattedTextFieldNombreProducto.getText();
        String NombreCliente = this.jFormattedTextFieldNombreCliente.getText();
        String NIT = this.jFormattedTextFieldNIT.getText();
        
        
        creditoCliente = Double.parseDouble(this.jTextFieldCreditoCliente.getText());
        pagoEfectivo = Double.parseDouble(this.jFormattedTextFieldPagoEfectivo.getText());
        usoCredito = Double.parseDouble(this.jFormattedTextFieldUsoCredito.getText());
        precio = Double.parseDouble(this.jFormattedTextFieldTotal.getText());
        
        //verfica los datos del producto para saber si uno fue seleccionado
        if(!(codigoProducto.equals("")||NombreProducto.equals("")))
        {
            //verifica la existencia de los productos en la tienda
            if(!(this.consulta.datosExistenciaProducto(codigoProducto, tiendaSleccionada,this.baseDeDatos).equals("0"))){
                //Verifica los datos del cliente quien hace la compra
                if(!(NIT.equals("")||NombreCliente.equals(""))){
                    if(!(usoCredito>creditoCliente)){
                        if(!((usoCredito+pagoEfectivo)>precio)){
                            if(((usoCredito+pagoEfectivo)==precio))
                            {
                                actualizacionDeCliente();
                                transaccionesDeInventario();
                                JOptionPane.showMessageDialog(this, "La transaccion fue correcta");
                                limpiezaFormulario();
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this, "Esta facturando un pago menor al precio del producto\nNo se puede realizar la transaccion");
                            }
                        }
                        else    
                        {
                            JOptionPane.showMessageDialog(this, "Esta facturando un pago mayor al precio del producto\nNo se puede realizar la transaccion");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "La cantidad de cradito a usar no la tiene disponible el cliente\nNo se puede realizar la transaccion");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No a especificado el cliente\nNo se puede realizar la transaccion");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "No hay existencia del producto haga un pedido del mismo en el apartado\nNo se puede realizar la transaccion");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun producto\nNo se puede realizar la transaccion");
        }
    }
    private void transaccionEspecial(){
        
    }
    private  void cargarEspecialDeDatos(){
        jLabel1.setText("Codigo del Pedido:");
        jFormattedTextFieldCodigoProducto.setText("");
        jButtonBuscarProducto.setVisible(false);
        jFormattedTextFieldPrecio.setText("0.00");
        jFormattedTextFieldNIT.setText("");
        jFormattedTextFieldNombreCliente.setText("");
        jButtonBuscarCliente.setVisible(false);
        jFormattedTextFieldPagoEfectivo.setText("0.00");
        jFormattedTextFieldUsoCredito.setEnabled(false);
    }
    /**
     * Realiza el descuento de existencia del producto comprado segun el codigo de tienda
     */
    private void transaccionesDeInventario(){
        for (int i = 0; i < this.ventasAcumuladas.size(); i++) {
            
            String codigoProducto = ventasAcumuladas.get(i).getCodigoProducto();
            int cantidadCompradas = ventasAcumuladas.get(i).getCantidad();
            String existencia =this.consulta.datosExistenciaProducto(codigoProducto, tiendaSleccionada,this.baseDeDatos);
            int cantidadOrigianl = Integer.valueOf(existencia);
            int nuevaExistencia = cantidadOrigianl-cantidadCompradas;
            
            Product actualizacion = new Product("", "", codigoProducto, nuevaExistencia, 0, "", 0, tiendaSleccionada);
            this.modificacion.modificarExistencia(actualizacion,this.baseDeDatos);
            this.registro.registroVenta(ventasAcumuladas.get(i),this.baseDeDatos);
        }
    }
    /**
     * Actualiza el credito del liente si fue utilizado
     */
    private void actualizacionDeCliente(){
        double creditoUsado = Double.valueOf(this.jFormattedTextFieldUsoCredito.getText());
        double creditoOriginal = Double.valueOf(this.consulta.datosCliente(this.jFormattedTextFieldNIT.getText(),this.baseDeDatos).get(2));
        double nuevoCredito = creditoOriginal-creditoUsado;
        this.modificacion.modificarCreditoCliente(this.jFormattedTextFieldNIT.getText(), String.valueOf(nuevoCredito),this.baseDeDatos);
    }
    /**
     * Limpia los campos de texto en la entrda garfica
     */
    private void limpiezaFormulario(){
        jFormattedTextFieldCodigoProducto.setText("");
        jFormattedTextFieldNombreProducto.setText("");
        jFormattedTextFieldPrecio.setText("0.00");
        jComboBoxCantidad.removeAllItems();
        jFormattedTextFieldNIT.setText("");
        jFormattedTextFieldNIT.setEditable(true);
        jTextFieldCreditoCliente.setText("0.00");
        jFormattedTextFieldNombreCliente.setText("");
        jFormattedTextFieldPagoEfectivo.setText("0.00");
        jFormattedTextFieldUsoCredito.setText("0.00");
        jFormattedTextFieldTotal.setText("0.00");
        this.modeloDeTabla=(DefaultTableModel) jTableProductos.getModel();
        this.modeloDeTabla.setNumRows(0);
        jTableProductos.setModel(modeloDeTabla);
        ventasAcumuladas.clear();
        jComboBoxYear.setEditable(true);
        jComboBoxYear.setSelectedIndex(0);
        jComboBoxMes.setEditable(true);
        jComboBoxMes.setSelectedIndex(0);
        jComboBoxDias.setEditable(true);
        jComboBoxDias.setSelectedIndex(0);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonTransaccion;
    private javax.swing.JComboBox<String> jComboBoxCantidad;
    private javax.swing.JComboBox<String> jComboBoxDias;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigoProducto;
    private javax.swing.JFormattedTextField jFormattedTextFieldNIT;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombreCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombreProducto;
    private javax.swing.JFormattedTextField jFormattedTextFieldPagoEfectivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecio;
    private javax.swing.JFormattedTextField jFormattedTextFieldTotal;
    private javax.swing.JFormattedTextField jFormattedTextFieldUsoCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldCreditoCliente;
    // End of variables declaration//GEN-END:variables
}
